services:
  jota-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jota_gateway
    network_mode: "host"
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 45s
    volumes:
      - ./data:/app/data
