"""initial schema

Revision ID: 21cb0cf4f6f9
Revises: 
Create Date: 2026-07-03 11:22:38.165997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21cb0cf4f6f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_agents', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stt_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stt_vad_thold', sa.Float(), nullable=False),
    sa.Column('tts_voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tts_speed', sa.Float(), nullable=False),
    sa.Column('barge_in_enabled', sa.Boolean(), nullable=False),
    sa.Column('barge_in_min_chars', sa.Integer(), nullable=False),
    sa.Column('output_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('silence_timeout_s', sa.Float(), nullable=False),
    sa.Column('max_silence_turns', sa.Integer(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('tool_calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('system_prompt_extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_key'), 'clients', ['client_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_client_key'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
